{
	"version": 1497344284,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/bullet-sheet0.png",
		"images/shellcasingright-sheet0.png",
		"images/shellcasingleft-sheet0.png",
		"images/early-sheet0.png",
		"images/early-sheet1.png",
		"images/ctrla-sheet0.png",
		"images/ctrldown-sheet0.png",
		"images/ctrlleft-sheet0.png",
		"images/ctrlright-sheet0.png",
		"images/ctrlb-sheet0.png",
		"images/ctrlpause-sheet0.png",
		"images/collidersolid-sheet0.png",
		"images/bgpollution.png",
		"images/bgpollutionsky.png",
		"images/groundwildgrass.png",
		"images/sprite-sheet0.png",
		"images/jumpthruwood.png",
		"images/whiskey-sheet0.png",
		"images/textpause-sheet0.png",
		"images/textdrinks.png",
		"media/shotgunshot.m4a",
		"media/shotgunshot.ogg",
		"media/gulp.m4a",
		"media/gulp.ogg",
		"media/bottle_clink.m4a",
		"media/bottle_clink.ogg",
		"media/squishy 1.m4a",
		"media/squishy 1.ogg",
		"media/squishy 2.m4a",
		"media/squishy 2.ogg",
		"loading-logo.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png"
	]
}