{
	"version": 1495090051,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/dir-sheet0.png",
		"images/sword-sheet0.png",
		"images/enemy_01-sheet0.png",
		"images/axe-sheet0.png",
		"images/bg.png",
		"images/enemydir-sheet0.png",
		"images/tiledbackground.png",
		"images/sprite-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/explosion-sheet0.png",
		"images/explosion-sheet1.png",
		"images/explosion-sheet2.png",
		"media/sword swing.m4a",
		"media/sword swing.ogg",
		"media/upgrade1.m4a",
		"media/upgrade1.ogg",
		"media/lazer ricochet.m4a",
		"media/lazer ricochet.ogg",
		"media/explosion 3.m4a",
		"media/explosion 3.ogg",
		"media/black gulch wbassperc.m4a",
		"media/black gulch wbassperc.ogg",
		"media/hot rain.m4a",
		"media/hot rain.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"pathfind.js"
	]
}