{
	"version": 1495221267,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/touch_act-sheet0.png",
		"images/touch_dn-sheet0.png",
		"images/touch_left-sheet0.png",
		"images/touch_right-sheet0.png",
		"images/touch_up-sheet0.png",
		"images/player-sheet0.png",
		"images/playerdirbox-sheet0.png",
		"images/enemypizza-sheet0.png",
		"images/enemygaycoconut-sheet0.png",
		"images/weaponbaton-sheet0.png",
		"images/weaponbattleaxe-sheet0.png",
		"images/mainscreenkeyboard-sheet0.png",
		"images/mainscreentouch-sheet0.png",
		"images/grass.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}