{
	"version": 1496221865,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/platform-sheet0.png",
		"images/pizzaslice-sheet0.png",
		"images/pizzaslice-sheet1.png",
		"images/leroy-sheet0.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/nametext.png",
		"images/dogicon-sheet0.png",
		"images/cloudtile-sheet0.png",
		"media/jump small.m4a",
		"media/jump small.ogg",
		"media/jump super.m4a",
		"media/jump super.ogg",
		"media/belch.m4a",
		"media/belch.ogg",
		"media/munch.m4a",
		"media/munch.ogg",
		"media/barking.m4a",
		"media/barking.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}